### ISSUE TITLE
FATAL: failed to allocate device memory for long state

### ISSUE THREAD

**Issue by dinho-afsn** [xbbricker/ccminer-cryptonight-mac#1] opened 2017-07-05 18:41 UTC
how to solve this error: FATAL: failed to allocate device memory for long state

**Comment by rizky** [comment] 2017-10-31 20:17
Did you solve this problem?

**Comment by hugheba** [comment] 2017-11-15 13:02
Same issue here. macOS 10.13.1, CUDA 9.0.222

**Comment by xbbricker** [comment] 2017-11-20 23:08
I think this is due to an incompatibility with the CUDA 9 driver. Can you see if the issue is fixed by running [CUDA 8](https://www.nvidia.com/object/macosx-cuda-8.0.90-driver.html)?

**Comment by rizky** [comment] 2017-11-22 14:24
Yes, It is solved by installing CUDA 8. Thanks @xbbricker!

**Comment by hugheba** [comment] 2017-11-24 19:21
How did you downgrade from CUDA 9?

**Closed as completed** 2020-07-14 03:00 UTC
